import { urlAttributeRules } from "../url-policy.js";

export const generatedUrlAttributeHelperLines = [
  `const __tachyonUrlAttributeRules = ${JSON.stringify(urlAttributeRules)};`,
  `const __tachyonUrlRule = (element, attribute) => { const normalizedElement = String(element).toLowerCase(); const normalizedAttribute = String(attribute).toLowerCase(); return __tachyonUrlAttributeRules.find((rule) => rule.attribute === normalizedAttribute && (rule.elements === "*" || rule.elements.includes(normalizedElement))); };`,
  `const __tachyonUrlUnsafe = (attribute) => ({ ok: false, message: "Unsafe URL for " + attribute + "." });`,
  `const __tachyonUrlHasControl = (value) => Array.from(value).some((character) => { const code = character.charCodeAt(0); return code <= 31 || code === 127; });`,
  `const __tachyonDecideSingleUrl = (attribute, purpose, value) => { const normalized = String(value).trim(); if (__tachyonUrlHasControl(normalized) || normalized.includes("\\\\") || normalized.startsWith("//")) return __tachyonUrlUnsafe(attribute); let decoded; try { decoded = decodeURIComponent(normalized); } catch { decoded = undefined; } if (decoded !== undefined && (__tachyonUrlHasControl(decoded) || decoded.includes("\\\\") || decoded.startsWith("//"))) return __tachyonUrlUnsafe(attribute); if (normalized === "") return { ok: true, value: normalized }; const rawScheme = /^([A-Za-z][A-Za-z0-9+.-]*):/.exec(normalized)?.[1]?.toLowerCase(); const decodedScheme = decoded === undefined ? undefined : /^([A-Za-z][A-Za-z0-9+.-]*):/.exec(decoded)?.[1]?.toLowerCase(); const scheme = rawScheme ?? decodedScheme; if (!scheme) return { ok: true, value: normalized }; if ((scheme === "mailto" || scheme === "tel") && purpose === "document-navigation") return { ok: true, value: normalized }; if (scheme !== "http" && scheme !== "https") return __tachyonUrlUnsafe(attribute); try { new URL(normalized); return { ok: true, value: normalized }; } catch { return __tachyonUrlUnsafe(attribute); } };`,
  `const __tachyonValidSrcsetDescriptor = (descriptor) => /^[1-9]\\d*w$/.test(descriptor) || (/^(?:\\d+(?:\\.\\d+)?|\\.\\d+)x$/.test(descriptor) && Number.parseFloat(descriptor.slice(0, -1)) > 0);`,
  `const __tachyonDecideSrcset = (attribute, value) => { const normalized = String(value).trim(); if (normalized === "") return __tachyonUrlUnsafe(attribute); for (const candidate of normalized.split(",")) { const tokens = candidate.trim().split(/[\\t\\n\\f\\r ]+/); const url = tokens[0]; if (!url || tokens.length > 2 || (tokens[1] !== undefined && !__tachyonValidSrcsetDescriptor(tokens[1]))) return __tachyonUrlUnsafe(attribute); const decision = __tachyonDecideSingleUrl(attribute, "subresource", url); if (!decision.ok) return decision; } return { ok: true, value: normalized }; };`,
  `const __tachyonSafeMetaRefreshContent = (value) => { const text = String(value); const urlTokens = text.match(/\\burl\\s*=/gi) ?? []; const match = /^\\s*\\d+(?:\\.\\d+)?\\s*(?:;\\s*url\\s*=\\s*(.*))?$/i.exec(text); if (__tachyonUrlHasControl(text) || !match || urlTokens.length > 1) throw new TypeError("Unsafe URL for content."); const rawTarget = match[1]?.trim(); if (rawTarget === undefined) return text.trim(); let target = rawTarget; if (rawTarget.startsWith('"') || rawTarget.startsWith("'")) { const quote = rawTarget[0]; if (rawTarget.length < 2 || !rawTarget.endsWith(quote) || rawTarget.slice(1, -1).includes(quote)) throw new TypeError("Unsafe URL for content."); target = rawTarget.slice(1, -1); } else if (rawTarget.includes('"') || rawTarget.includes("'")) throw new TypeError("Unsafe URL for content."); const decision = __tachyonDecideSingleUrl("content", "document-navigation", target); if (!decision.ok) throw new TypeError(decision.message); return text.trim(); };`,
  `const __tachyonSafeUrlAttribute = (element, attribute, value) => { const rule = __tachyonUrlRule(element, attribute); if (!rule) throw new TypeError("Invalid URL context for " + attribute + "."); const result = rule.kind === "srcset" ? __tachyonDecideSrcset(attribute, value) : __tachyonDecideSingleUrl(attribute, rule.purpose, value); if (!result.ok) throw new TypeError(result.message); return result.value; };`,
] as const;
